config/routes.rb
Rails.application.routes.draw do
  resources :sales
  resources :accounts
  devise_for :users
  root 'accounts#index'

  get "customer_sales" => "sales#customer_sales"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/account.rb
class Account < ApplicationRecord
  has_many :sales
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/sale.rb
class Sale < ApplicationRecord
  belongs_to :account
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  # GET /accounts or /accounts.json
  def index
    @accounts = Account.all
    @accounts = @accounts.where(["nombre LIKE :filter", :filter => "%" + params[:filter] + "%"]) unless params[:filter].blank?
    @accounts = @accounts = @accounts.where(:sale_id => params[:sale_id]) if params[:sale_id]
  end

  # GET /accounts/1 or /accounts/1.json
  def show
  end

  # GET /accounts/new
  def new
    @account = Account.new
  end

  # GET /accounts/1/edit
  def edit
  end

  # POST /accounts or /accounts.json
  def create
    @account = Account.new(account_params)

    respond_to do |format|
      if @account.save
        format.html { redirect_to @account, notice: "Account was successfully created." }
        format.json { render :show, status: :created, location: @account }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accounts/1 or /accounts/1.json
  def update
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to @account, notice: "Account was successfully updated." }
        format.json { render :show, status: :ok, location: @account }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1 or /accounts/1.json
  def destroy
    @account.destroy
    respond_to do |format|
      format.html { redirect_to accounts_url, notice: "Account was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = Account.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def account_params
      params.require(:account).permit(:nombre, :dni, :celular)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_action :set_sale, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  # GET /sales or /sales.json
  def index
    @sales = Sale.all
  end

  # GET /sales/1 or /sales/1.json
  def show
  end

  # GET /sales/new
  def new
    @sale = Sale.new
  end

  # GET /sales/1/edit
  def edit
  end

  # POST /sales or /sales.json
  def create
    @sale = Sale.new(sale_params)

    respond_to do |format|
      if @sale.save
        format.html { redirect_to @sale, notice: "Sale was successfully created." }
        format.json { render :show, status: :created, location: @sale }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sales/1 or /sales/1.json
  def update
    respond_to do |format|
      if @sale.update(sale_params)
        format.html { redirect_to @sale, notice: "Sale was successfully updated." }
        format.json { render :show, status: :ok, location: @sale }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sales/1 or /sales/1.json
  def destroy
    @sale.destroy
    respond_to do |format|
      format.html { redirect_to sales_url, notice: "Sale was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sale
      @sale = Sale.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def sale_params
      params.require(:sale).permit(:descripcion, :precio, :monto_cliente, :ganancia, :vendido, :pagado, :account_id)
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sales_helper.rb
module SalesHelper
  def iconify_active(vendido)
    if vendido == true
      return '<span class="badge bg-success">Sí</span>'
    else
      return '<span class="badge bg-danger">No</span>'
    end
  end
end
def iconify_active(pagado)
    if pagado == true
      return '<span class="badge bg-success">Sí</span>'
    else
      return '<span class="badge bg-danger">No</span>'
    end
  end

app/views/accounts/_form.html.erb
  <%= form_with(model: account) do |form| %>
<div class="modal-body">

    <% if account.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(account.errors.count, "error") %> prohibited this account from being saved:</h2>

        <ul>
          <% account.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= form.label :nombre %>
      <%= form.text_field :nombre %>
    </div>

    <div class="field">
      <%= form.label :dni %>
      <%= form.number_field :dni %>
    </div>

    <div class="field">
      <%= form.label :celular %>
      <%= form.number_field :celular %>
    </div>

    <div class="actions">
      <%= form.submit %>
    </div>


</div>
  <% end %>

app/views/accounts/_new.html.erb
<div class="modal fade" id="nuevaFicha" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="staticBackdropLabel">Modal title</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        ...
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Understood</button>
      </div>
    </div>
  </div>
</div>

app/views/accounts/edit.html.erb
<h1>Editing Account</h1>

<%= render 'form', account: @account %>

<%= link_to 'Show', @account %> |
<%= link_to 'Back', accounts_path %>

app/views/accounts/index.html.erb
<br><br>
<p id="notice"><%= notice %></p>
<div class="modal fade" id="nuevaFicha" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Nueva ficha</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <%= form_with(model: Account.new) do |form| %>
        <div class="modal-body">
            <div class="field">
              <%= form.label :nombre %>
              <%= form.text_field :nombre, class: "form-control" %>
            </div>
            <div class="field">
              <%= "DNI" %>
              <%= form.number_field :dni, class: "form-control" %>
            </div>
            <div class="field">
              <%= "Número de celular" %>
              <%= form.number_field :celular, class: "form-control" %>
            </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
          <button type="submit" class="btn btn-primary">Guardar cambios</button>
        </div>
      <% end %>
    </div>
  </div>
</div>
<a href="#" class="btn btn-light" data-bs-toggle="modal" data-bs-target="#nuevaFicha" id="margen">Nueva ficha</a>
<form method="GET" action="/accounts">
  <input type="text" name="filter" placeholder="Nombre">
  <input type="submit" class="btn btn-dark" value="Buscar" />
</form>
<table>
  <thead>
    <!--<tr>
      <th>Nombre</th>
      <th>Dni</th>
      <th>Celular</th>
      <th colspan="3"></th>
    </tr>-->
  </thead>

  <tbody>
    <% @accounts.each do |account| %>
      <tr>
        <!--<td><%= account.nombre %></td>
        <td><%= account.dni %></td>
        <td><%= account.celular %></td>
        <td><%= link_to 'Show', account %></td>
        <td><%= link_to 'Edit', edit_account_path(account) %></td>
        <td><%= link_to 'Destroy', account, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
      </tr>
      <div class="list-group">
        <a href="#" class="list-group-item list-group-item-action" data-bs-toggle="modal" data-bs-target="#exampleModal"><%= account.nombre %></a>
      </div>

    <% end %>
  </tbody>
</table>

<br>

app/views/accounts/new.html.erb
<h1>New Account</h1>

<%= render 'form', account: @account %>

<%= link_to 'Back', accounts_path %>

app/views/accounts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @account.nombre %>
</p>

<p>
  <strong>Dni:</strong>
  <%= @account.dni %>
</p>

<p>
  <strong>Celular:</strong>
  <%= @account.celular %>
</p>

<%= link_to 'Edit', edit_account_path(@account) %> |
<%= link_to 'Back', accounts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bonfire</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>

    <br><br>
    <%= yield %>
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
            ...
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            <button type="button" class="btn btn-primary">Save changes</button>
          </div>
        </div>
      </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
  </body>
</html>

app/views/sales/_customer_sales_modal.html.erb
<div class="modal fade" id="sales<%= account_id %>" tabindex="-1" aria-labelledby="customer_sales" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Compras cliente</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body" id="customer_sales_data">
        <%= Sale.where(:account_id => account_id).inspect %>
      </div>  
    </div>
  </div>
</div>

app/views/sales/_form.html.erb
<%= form_with(model: sale) do |form| %>
  <% if sale.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sale.errors.count, "error") %> prohibited this sale from being saved:</h2>

      <ul>
        <% sale.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :descripcion %>
    <%= form.text_field :descripcion %>
  </div>

  <div class="field">
    <%= form.label :precio %>
    <%= form.number_field :precio %>
  </div>

  <div class="field">
    <%= form.label :monto_cliente %>
    <%= form.number_field :monto_cliente %>
  </div>

  <div class="field">
    <%= form.label :ganancia %>
    <%= form.number_field :ganancia %>
  </div>

  <div class="field">
    <%= form.label :vendido %>
    <%= form.check_box :vendido %>
  </div>

  <div class="field">
    <%= form.label :pagado %>
    <%= form.check_box :pagado %>
  </div>

  <div class="field">
    <%= form.label :account_id %>
    <%= form.collection_select :account_id, Account.all, :id, :nombre, { :include_blank => true } %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/sales/edit.html.erb
<h1>Editing Sale</h1>

<%= render 'form', sale: @sale %>

<%= link_to 'Show', @sale %> |
<%= link_to 'Back', sales_path %>

app/views/sales/index.html.erb
<p id="notice"><%= notice %></p>
<br><br>
<div class="modal fade" id="nuevaVenta" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Nueva venta</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <%= form_with(model: Sale.new) do |form| %>
        <div class="modal-body">
          <div class="field">
            <%= "Descripción" %>
            <%= form.text_field :descripcion, class: "form-control" %>
          </div>

          <div class="field">
            <%= form.label :precio %>
            <%= form.number_field :precio, class: "form-control" %>
          </div>

          <div class="field">
            <%= "Monto para el cliente" %>
            <%= form.number_field :monto_cliente, class: "form-control" %>
          </div>

          <div class="field">
            <%= form.label :ganancia %>
            <%= form.number_field :ganancia, class: "form-control" %>
          </div>

          <div class="field">
            <%= "¿Está vendido?" %>
            <br>
            <%= form.check_box :vendido, class:"form-check-input" %>
          </div>

          <div class="field">
            <%= "¿Está pagado?" %>
            <br>
            <%= form.check_box :pagado, class:"form-check-input" %>
          </div>

          <div class="field">
            <%= "Cuenta" %>
            <%= form.collection_select :account_id, Account.all, :id, :nombre, { :include_blank => true }, {class: 'form-select'} %>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
          <button type="submit" class="btn btn-primary">Guardar cambios</button>
        </div>
      <% end %>
    </div>
  </div>
</div>


<div class="modal fade" id="editarVenta" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Editar venta</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <%= form_with(model: Sale.new) do |form| %>
        <div class="modal-body">
          <div class="field">
            <%= "Descripción" %>
            <%= form.text_field :descripcion, class: "form-control" %>
          </div>

          <div class="field">
            <%= form.label :precio %>
            <%= form.number_field :precio, class: "form-control" %>
          </div>

          <div class="field">
            <%= "Monto para el cliente" %>
            <%= form.number_field :monto_cliente, class: "form-control" %>
          </div>

          <div class="field">
            <%= form.label :ganancia %>
            <%= form.number_field :ganancia, class: "form-control" %>
          </div>

          <div class="field">
            <%= "¿Está vendido?" %>
            <br>
            <%= form.check_box :vendido, class:"form-check-input" %>
          </div>

          <div class="field">
            <%= "¿Está pagado?" %>
            <br>
            <%= form.check_box :pagado, class:"form-check-input" %>
          </div>

          <div class="field">
            <%= "Cuenta" %>
            <%= form.collection_select :account_id, Account.all, :id, :nombre, { :include_blank => true }, {class: 'form-select'} %>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
          <button type="submit" class="btn btn-primary">Guardar cambios</button>
        </div>
      <% end %>
    </div>
  </div>
</div>
<a href="#" class="btn btn-light" data-bs-toggle="modal" data-bs-target="#nuevaVenta" id="margen">Nueva venta</a>
<br><br>
<table class="table table-hover table-light">
  <thead>
  <tr>
      <th>Descripción</th>
      <th>Precio</th>
      <th>Monto cliente</th>
      <th>Ganancia</th>
      <th>Vendido</th>
      <th>Pagado</th>
      <th>Cuenta</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sales.each do |sale| %>
      <tr>
        <td><%= sale.descripcion %></td>
        <td><%= "$"+sale.precio.to_s %></td>
        <td><%= "$"+sale.monto_cliente.to_s %></td>
        <td><%= "$"+sale.ganancia.to_s %></td>
        <td><%= raw iconify_active(sale.vendido) %></td>
        <td><%= raw iconify_active(sale.pagado) %></td>
        <td><%= link_to sale.account.nombre, "#", "data-bs-toggle"=>"modal", "data-bs-target"=>"#sales#{sale.account_id}", "data-customer-id"=>sale.account_id, :id => "customer_sales_link"  %></td>
        <td><%= link_to 'Editar', edit_sale_path(sale), class: "btn btn-primary", style: "color:white" %></td>
        <td><%= link_to 'Eliminar', sale, class: "btn btn-primary", style: "color:white",  method: :delete, data: { confirm: '¿Está seguro?' }%></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% @sales.map(&:account_id).each do | account_id | %>
  <%= render :partial => "sales/customer_sales_modal", :locals => {:account_id => account_id} %>
<% end %>


<br>

app/views/sales/new.html.erb
<h1>New Sale</h1>

<%= render 'form', sale: @sale %>

<%= link_to 'Back', sales_path %>

app/views/sales/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Descripcion:</strong>
  <%= @sale.descripcion %>
</p>

<p>
  <strong>Precio:</strong>
  <%= @sale.precio %>
</p>

<p>
  <strong>Monto cliente:</strong>
  <%= @sale.monto_cliente %>
</p>

<p>
  <strong>Ganancia:</strong>
  <%= @sale.ganancia %>
</p>

<p>
  <strong>Vendido:</strong>
  <%= @sale.vendido %>
</p>

<p>
  <strong>Pagado:</strong>
  <%= @sale.pagado %>
</p>

<p>
  <strong>Account:</strong>
  <%= @sale.account_id %>
</p>

<%= link_to 'Edit', edit_sale_path(@sale) %> |
<%= link_to 'Back', sales_path %>

app/views/shared/_main_menu.html.erb
<div class="collapse navbar-collapse show" id="navbarWithDropdown">
  <ul class="navbar-nav">
    <li class="nav-item">
      <%= link_to "FICHAS", accounts_url, class: 'nav-link' , style:"color:black" %>
    </li>
    <li class="nav-item">
      <%= link_to "VENTAS", sales_url, class: 'nav-link', style:"color:black" %>
    </li>
  </ul>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg fixed-top navbar-dark " style="background-color: #FFFFFF">
  <div class="container-fluid">
    <a class="navbar-brand" style="color:black" href="<%= root_url %>">Bonfire<%= image_tag "fogata.jpeg", :class => "style_image" %></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon" ></span>
    </button>

    <%= render 'shared/main_menu' %>
    <%= render 'shared/user_menu' %>
  </div>
</nav>

app/views/shared/_user_menu.html.erb
<div class="collapse navbar-collapse show" id="navbarWithDropdown">
  <ul class="navbar-nav">
    <% if user_signed_in? %>
      <li class="nav-item">
        <%= link_to "EDITAR PERFIL", edit_user_registration_path, class: 'nav-link' , style:"color:black"  %>
      </li>
      <li class="nav-item">
        <%= link_to "CERRAR SESIÓN", destroy_user_session_path, class: 'nav-link' , style:"color:black",  method: :delete  %>
      </li>
    <% end %>
  </ul>
</div>